# -*- coding: utf-8 -*-
"""Kalendarz_akcji.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bfU5lwdNa2GOPWmQ9-URaf30VnlBzQC0
"""

# -*- coding: utf-8 -*-
"""Kalendarz_akcji.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bfU5lwdNa2GOPWmQ9-URaf30VnlBzQC0
"""

# -*- coding: utf-8 -*-
"""Kalendarz_akcji.ipynb"""

import openpyxl
import streamlit as st
import pandas as pd
import numpy as np
import altair as alt
import plotly.express as px
import plotly.graph_objects as go
from urllib.request import urlopen
import json
import io
import datetime
from streamlit_calendar import calendar

st.set_page_config(page_title='Kalendarz akcji', layout='wide')
st.title("📆 Kalendarz akcji")

# 🎨 PALETY
palettes = {
    "Żywa": [
        "#FF6B6B", "#FF922B", "#FFD93D", "#6BCB77", "#4D96FF", "#845EC2",
        "#FF5E78", "#00C9A7", "#FF4C4C", "#FF7F3F", "#FFCD38", "#28C76F",
        "#2E86DE", "#9D4EDD"
    ],
    "Pastelowa": [
        "#FFB3BA", "#FFDFBA", "#FFFFBA", "#BAFFC9", "#BAE1FF", "#E0BBE4",
        "#FFCCE5", "#C2F0FC", "#FFE5E5", "#FFF1BA", "#E6FFBA", "#BAFFE1",
        "#D4E7FF", "#F3D1FF"
    ],
    "Odcienie niebieskiego": [
        "#001F3F", "#003566", "#00509E", "#0074D9", "#419DFF", "#7ABFFF",
        "#A8D8FF", "#D6ECFF", "#002855", "#004E92", "#1A73E8", "#5DA9FF",
        "#96C7FF", "#CBE2FF"
    ]
}
# 📑 ZAKŁADKI NA POCZĄTKU
tab1, tab2 = st.tabs(["📆 Kalendarz główny", "📆 Kalendarz szczegółowy"])

selected_palette = st.selectbox("🎨 Wybierz paletę kolorów", list(palettes.keys()))

with tab1:
    st.subheader("📅 Widok kalendarza")
    uploaded_file = st.file_uploader("📄 Wczytaj plik Excel z akcjami", type=["xlsx"])
    st.subheader("🎨 Wybierz paletę kolorów dla kalendarza")
    selected_palette_tab1 = st.selectbox("Paleta dla kalendarza", list(palettes.keys()), key="palette_tab1")

    if uploaded_file:
        df = pd.read_excel(uploaded_file)
        df["Data startu"] = pd.to_datetime(df["Data startu"])
        df["Data końca"] = pd.to_datetime(df["Data końca"])

        palette = palettes[selected_palette_tab1]
        unique_names = df["Nazwa akcji"].unique()
        color_map = {name: palette[i % len(palette)] for i, name in enumerate(unique_names)}

        events = []
        for _, row in df.iterrows():
            events.append({
                "start": row["Data startu"].strftime("%Y-%m-%d"),
                "end": row["Data końca"].strftime("%Y-%m-%d"),
                "title": row["Nazwa akcji"],
                "color": color_map[row["Nazwa akcji"]],
            })

        calendar_options = {
            "initialView": "dayGridMonth",
            "headerToolbar": {"left": "prev,next today", "center": "title", "right": "dayGridMonth,dayGridWeek,dayGridDay"},
            "height": 750,
            "contentHeight": "auto",
            "aspectRatio": 1.5,
            "navLinks": True,
            "editable": False,
            "dayMaxEventRows": True,
            "locale": "pl",
            "firstDay": 1
        }

        calendar(events=events, options=calendar_options)
    else:
        st.info("📥 Najpierw wczytaj plik Excel, aby zobaczyć kalendarz.")

with tab2:
    st.subheader("📊 Statystyki akcji")
    if uploaded_file:
        total_events = len(df)
        unique_events = df["Nazwa akcji"].nunique()
        longest = (df["Data końca"] - df["Data startu"]).max().days + 1

        st.markdown(f"""
        ✅ **Łączna liczba akcji:** {total_events}  
        ✅ **Unikalne akcje:** {unique_events}  
        ✅ **Najdłuższa akcja trwała:** {longest} dni
        """)

        df["Miesiąc"] = df["Data startu"].dt.to_period("M").astype(str)
        month_counts = df.groupby("Miesiąc").size().reset_index(name="Liczba akcji")

        fig = px.bar(month_counts, x="Miesiąc", y="Liczba akcji",
                     title="📈 Liczba akcji w miesiącach",
                     color="Liczba akcji", color_continuous_scale="Blues")

        st.plotly_chart(fig, use_container_width=True)
    else:
        st.info("📥 Najpierw wczytaj plik Excel, aby zobaczyć statystyki.")
